# Generated by Django 5.0 on 2024-01-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_id', models.CharField(max_length=36, unique=True)),
                ('tv_serie_id', models.CharField(max_length=36, unique=True)),
                ('id_imdb', models.CharField(max_length=36, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('actors', models.TextField()),
                ('genre', models.TextField()),
                ('media_type', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('type_film', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
