# Generated by Django 5.0 on 2024-01-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_movies_delete_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
