# Generated by Django 5.0 on 2024-01-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_movies_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='actors',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='id_imdb',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='media_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_id',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='tv_serie_id',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='type_film',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
