# Generated by Django 5.0 on 2024-01-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_movies_actors_alter_movies_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='id_imdb',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_id',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='tv_serie_id',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
