# Generated by Django 5.0 on 2024-01-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_movies_id_imdb_alter_movies_movie_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='conver_back',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='conver_front',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
