# Generated by Django 5.0 on 2024-01-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_movies_conver_back_movies_conver_front'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='conver_back',
            new_name='cover_back',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='conver_front',
            new_name='cover_front',
        ),
    ]
