# Generated by Django 5.0 on 2024-01-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_rename_conver_back_movies_cover_back_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='cover_back',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='cover_front',
        ),
        migrations.AddField(
            model_name='movies',
            name='img_back',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='img_front',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
