# Generated by Django 5.0 on 2024-01-04 14:34

import films.models
from django.db import migrations, models

def populate_cover_fields(apps, schema_editor):
    Movies = apps.get_model('films', 'Movies')
    for movie in Movies.objects.all():
        movie.url_img_front = f'covers/{movie.img_front}.jpg'
        movie.url_img_back = f'covers/{movie.img_back}.jpg'
        movie.save()

class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_movies_cover_back_movies_cover_front'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='cover_back',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='cover_front',
        ),
        migrations.AddField(
            model_name='movies',
            name='url_img_back',
            field=models.ImageField(null=True, upload_to=films.models.get_img_back_upload_path),
        ),
        migrations.AddField(
            model_name='movies',
            name='url_img_front',
            field=models.ImageField(null=True, upload_to=films.models.get_img_front_upload_path),
        ),
        migrations.RunPython(populate_cover_fields),
    ]
